version: '3'

services:
  db:
    image: mariadb
    restart: always
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    environment:
      MYSQL_DATABASE: "simicrofin_jdgp"
      MYSQL_USER: "evillanueva"
      MYSQL_PASSWORD: "evillanueva"
      MYSQL_ROOT_PASSWORD: "docker-root"

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: dmd_web
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
